### ISSUE TITLE
csvgrep -r doesn't find matches across newlines

### ISSUE THREAD

**Issue by gabebw** [onyxfish/csvkit#368]
I'm using csvkit 0.9.0.

Given the following CSV in `test.csv`:

```
user_id,body
gabebw,"IRC
AIM"
```

`csvgrep` can find the row when matching on `IRC`, which is on the first line:

```
$ csvgrep -c body -r IRC test.csv
user_id,body
gabebw,"IRC
AIM"
```

But when I try to match on `AIM`, which is on a newline but still part of the row, `csvgrep` does not find the row:

```
$ csvgrep -c body -r AIM test.csv
user_id,body
```

Am I using `-r` incorrectly, or maybe passing it the wrong input?

**Comment by onyxfish** [comment]
Hi Gabe! This looks like a legit bug. I probably need to add a flag to the regex compile. I'll look into it! Thanks for opening an issue!

**Comment by gabebw** [comment]
Absolutely. If you need someone to test new code or anything, just let me know. I know how hard it is to keep up with even a semi-popular open source project.

**Comment by edwardros** [comment]
I'm not sure that this is the issue:

    csvgrep -c body -r RC test.csv

also returns no rows. This is because (at least as of 0.9.1/0.9.2) it uses re.match instead of re.search.

Simply changing match to search on lines 105 and 116 of grep.py resolve this issue.

**Comment by jpmckinney** [comment]
Thanks @edwardros ! `match` has been there since the tool was introduced in b8c6bb94. Fixed in #516

**Comment by antonkryvko** [comment]
Hi! I think problem is still here:
`csvgrep -c 2 -r '\d' test.csv`
returns the header instead of matched lines. Probably, it's something with flag.

**Comment by jpmckinney** [comment]
What is your test.csv?

**Comment by antonkryvko** [comment]
It's a datable with combined text and digits. Something like this:

```
full_name,info,aliments,okrug,cancel_registration,registration_date,nomination,oblast,
Кістіон Володимир Євсевійович,"народився 31 05 1965 року в селі Довжок Ямпільського району Вінницької області, громадянин України, протягом останніх п’яти років проживає на території України, освіта вища, Віце-прем’єр-міністр України, безпартійний, проживає в місті Києві, судимість відсутня, самовисування.",,11, ,12.06.2019,Самовисування,Вінницька область
```
I want to return date from the second column using `(\d{1,2})\s(\d{2})\s(\d{4})`. It works on [https://pythex.org/](url), but doesn't work in csvgrep.

**Comment by jpmckinney** [comment]
When I run:

    echo 'full_name,info,aliments,okrug,cancel_registration,registration_date,nomination,oblast,
    Кістіон Володимир Євсевійович,"народився 31 05 1965 року в селі Довжок Ямпільського району Вінницької області, громадянин України, протягом останніх п’яти років проживає на території України, освіта вища, Віце-прем’єр-міністр України, безпартійний, проживає в місті Києві, судимість відсутня, самовисування.",,11, ,12.06.2019,Самовисування,Вінницька област
    ' | csvgrep -c 2 -r '\d'

The row matches.

**Comment by antonkryvko** [comment]
Deeply sorry, I'd used 0.9.1-2 version from Ubuntu repository, which has [a bug](https://github.com/wireservice/csvkit/issues/368#issuecomment-137656152), resolved in the present version. Now I've installed 1.0.4 from PyPi and everything is all right.
